* First Steps

** Create Your First Website
Once Kulfon is installed, you will have access to the `kulfon` command. First, let's create a new project:

#+BEGIN_SRC bash
kulfon new my-project
#+END_SRC

** Run in ~Development~ Mode

Enter the newly created project directory:

#+BEGIN_SRC bash
cd my-project
#+END_SRC

Invoke ~kulfon~'s ~server~ command to run it in ~development~ mode

#+BEGIN_SRC bash
kulfon serve
#+END_SRC

Go to ~http://localhost:3000~ to check your website.

For more commands, just type:

#+BEGIN_SRC bash
kulfon
#+END_SRC
** Create Page

Kulfon provides a set of CLI commands to facilitate the most common tasks. One
of such tasks is page creation.

Use ~create~ command to create a new Markdown or Org Mode page. By default, the
page is created as a Markdown document.

#+BEGIN_SRC bash
kulfon create page "My new lovely page"
#+END_SRC
#+BEGIN_SRC bash
Created `website/pages/my-new-lovely-page.md`
#+END_SRC

If you would like to create an Org Mode page, use ~--format~ parameter directly
on the command line (or set the prefered page format in your ~config.yaml~):

#+BEGIN_SRC bash
kulfon create page "My new lovely page" --format org
#+END_SRC
#+BEGIN_SRC bash
Created `website/pages/my-new-lovely-page.org`
#+END_SRC
